### ISSUE TITLE
SyntaxError: Unexpected token

### ISSUE THREAD

**Issue by lovecn** [vladocar/screenshoteer#25]
```js
[root@VM_0_14_centos ~]# screenshoteer  --url https://www.baidu.com
/usr/lib/node_modules/screenshoteer/index.js:33
(async () => {
       ^

SyntaxError: Unexpected token (
    at createScript (vm.js:56:10)
    at Object.runInThisContext (vm.js:97:10)
    at Module._compile (module.js:549:28)
    at Object.Module._extensions..js (module.js:586:10)
    at Module.load (module.js:494:32)
    at tryModuleLoad (module.js:453:12)
    at Function.Module._load (module.js:445:3)
    at Module.runMain (module.js:611:10)
    at run (bootstrap_node.js:394:7)
    at startup (bootstrap_node.js:160:9)

[root@VM_0_14_centos ~]# node -v
v6.14.3
[root@VM_0_14_centos ~]# npm -v
3.10.10
```

**Comment by vladocar** [comment]
Why do you have "#" before screenshoteer?

**Comment by lovecn** [comment]
@vladocar it is just cli prompt

**Comment by vladocar** [comment]
I tried your example and it worked perfectly on my pc. Unfortunately I don't know why it doesn't work on your PC.
